#!/bin/bash
CHRONOS_HOME="/opt/marathon"
MESOS_HOME="/usr/share/java"
MESOS_LIB="/usr/local/lib/libmesos.so"

ZK_HOSTS="$(cat /etc/mesos/zk)"

#HOSTNAME=localhost
PORT=8080

# Mesos requirement
#MASTER=zk://localhost:2181/mesos
MASTER="$(cat /etc/mesos/zk)"
