#!/bin/bash
MARATHON_HOME="/opt/marathon"
MESOS_HOME="/usr/share/java"
MESOS_LIB="/usr/local/lib/libmesos.so"

#LOG_DIR="/var/log/marathon"
# if you want marathon to bind to specific port,
# otherwise random port between 30000-60000 is choosen
#export LIBPROCESS_PORT=5070

#EXTRA_OPTS=
