#!/bin/sh
# Start/stop the marathon.
#
### BEGIN INIT INFO
# Provides:          marathon
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Should-Start:      $network $named slapd autofs ypbind nscd nslcd
# Should-Stop:       $network $named slapd autofs ypbind nscd nslcd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: marathon
# Description:       marathon
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="marathon daemon"
NAME=marathon
SCRIPTNAME=$0
LOG_DIR="/var/log/marathon"


. /etc/default/marathon

DAEMON="${MARATHON_HOME}/bin/marathon"
PIDFILE=/var/run/${NAME}.pid
# set these to match your environment
CHRONOS_HOME=/opt/marathon
MESOS_HOME=/opt/mesos

export LIBPROCESS_PORT=5060

if [ "$(id -u)" -ne "0" ]; then
  echo "you must be root to start ${DESC}"
  exit 1
fi

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting service scheduler" "marathon"
    echo "$DAEMON $EXTRA_OPTS"
    echo "[$(date)] Starting marathon: $DAEMON" >> $LOG_DIR/marathon.log
    start-stop-daemon --start --quiet --background \
        --pidfile $PIDFILE --make-pidfile \
        --startas /bin/bash -- -c "exec $DAEMON ${EXTRA_OPTS} >> $LOG_DIR/marathon.log 2>&1"
    log_end_msg $?
  ;;
  stop)
    log_daemon_msg "Stopping service scheduler" "${NAME}"
    killproc -p $PIDFILE $DAEMON
    RETVAL=$?
    [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
    log_end_msg $RETVAL
  ;;
  restart)
    log_daemon_msg "Restarting periodic command scheduler" "${NAME}"
    $0 stop
    sleep 5
    $0 start
  ;;
  reload|force-reload)
    log_daemon_msg "Reloading configuration files for periodic command scheduler" "${NAME}"
    # cron reloads automatically
    log_end_msg 0
  ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
    ;;
  *)
    log_action_msg "Usage: ${SCRIPTNAME} {start|stop|status|restart|reload|force-reload}"
    exit 2
  ;;
esac
exit 0

