#!/bin/sh
set -e

if [ -x "/etc/init.d/marathon" ]; then
        update-rc.d marathon defaults 95 10 >/dev/null
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d marathon start || true
        else
                /etc/init.d/marathon start || true
        fi
fi
